#ifndef OBICALL_STATUS_H
#define OBICALL_STATUS_H

#include <stdint.h>

#include "obicall/platform.h"
#include "obicall/obicall_export.h"

OBICALL_BEGIN_DECLS

/* int32_t-backed so the enum has a fixed wire width across compilers/ABIs. */
typedef int32_t obicall_status_t;

enum obicall_status_code {
    OBICALL_OK = 0,

    /* Argument / contract errors: 1-19 */
    OBICALL_ERR_INVALID_ARGUMENT = 1,
    OBICALL_ERR_NULL_POINTER = 2,
    OBICALL_ERR_OUT_OF_RANGE = 3,
    OBICALL_ERR_BUFFER_TOO_SMALL = 4,
    OBICALL_ERR_NOT_FOUND = 5,
    OBICALL_ERR_ALREADY_EXISTS = 6,
    OBICALL_ERR_UNSUPPORTED = 7,

    /* ABI / plugin errors: 20-39 */
    OBICALL_ERR_ABI_VERSION_MISMATCH = 20,
    OBICALL_ERR_ABI_STRUCT_SIZE_MISMATCH = 21,
    OBICALL_ERR_SYMBOL_NOT_FOUND = 22,
    OBICALL_ERR_ARCHITECTURE_MISMATCH = 23,
    OBICALL_ERR_ARTIFACT_INTEGRITY = 24,
    OBICALL_ERR_DEPENDENCY_CYCLE = 25,
    OBICALL_ERR_DEPENDENCY_MISSING = 26,
    OBICALL_ERR_CONFORMANCE_FAILED = 27,
    OBICALL_ERR_LOAD_FAILED = 28,

    /* Validation / admission errors: 40-59 */
    OBICALL_ERR_VALIDATION_NON_FINITE = 40,
    OBICALL_ERR_VALIDATION_DIMENSION = 41,
    OBICALL_ERR_VALIDATION_COVARIANCE = 42,
    OBICALL_ERR_VALIDATION_SEQUENCE = 43,
    OBICALL_ERR_VALIDATION_TIMING = 44,
    OBICALL_ERR_ADMISSION_DUPLICATE = 45,
    OBICALL_ERR_ADMISSION_LATE = 46,
    OBICALL_ERR_ADMISSION_OVERFLOW = 47,

    /* Wire / IO errors: 60-79 */
    OBICALL_ERR_WIRE_MALFORMED = 60,
    OBICALL_ERR_WIRE_TOO_LARGE = 61,
    OBICALL_ERR_WIRE_VERSION_UNSUPPORTED = 62,
    OBICALL_ERR_WIRE_CHECKSUM = 63,
    OBICALL_ERR_IO = 64,
    OBICALL_ERR_TIMEOUT = 65,
    OBICALL_ERR_AUTH = 66,
    OBICALL_ERR_CONNECTION_CLOSED = 67,

    /* Gate / publication errors: 80-99 */
    OBICALL_ERR_GATE_NOT_OWNER = 80,
    OBICALL_ERR_GATE_STALE_EPOCH = 81,
    OBICALL_ERR_GATE_DUPLICATE_WINDOW = 82,
    OBICALL_ERR_GATE_EXPIRED = 83,
    OBICALL_ERR_GATE_INCOMPATIBLE = 84,
    OBICALL_ERR_GATE_NOT_READY = 85,
    OBICALL_ERR_GATE_PERSISTENCE = 86,

    /* Process / runtime errors: 100-119 */
    OBICALL_ERR_PROCESS_SPAWN = 100,
    OBICALL_ERR_PROCESS_NOT_RUNNING = 101,
    OBICALL_ERR_ALREADY_RUNNING = 102,

    /* DGT policy errors: 120-129 */
    OBICALL_ERR_DGT_NO_ELIGIBLE_ACTION = 120,
    OBICALL_ERR_DGT_INVALID_SCORE = 121,

    OBICALL_ERR_INTERNAL = 255
};

OBICALL_API const char* OBICALL_CALL obicall_status_string(obicall_status_t status);

OBICALL_END_DECLS

#endif /* OBICALL_STATUS_H */
